### ISSUE TITLE
[kinda fixed] Program exits with `Can't locate LWP/UserAgent.pm in @INC`

### ISSUE THREAD

**Issue by GNUxeava** [dimethyltriptamine/peertube-cli#1]
I believe it is due to missing modules
Here is the full error
```
Can't locate LWP/UserAgent.pm in @INC (you may need to install the LWP::UserAgent module) (@INC contains: /home/user/perl5/lib/perl5/5.34.0/x86_64-linux-thread-multi /home/user/perl5/lib/perl5/5.34.0 /home/user/perl5/lib/perl5/x86_64-linux-thread-multi /home/user/perl5/lib/perl5 /usr/lib/perl5/5.34/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.34/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.34/core_perl /usr/share/perl5/core_perl) at ./peertube-cli.pl line 7.
BEGIN failed--compilation aborted at ./peertube-cli.pl line 7.
```

# Possible fix
This might be a possible fix. I installed the modules one by one as it spat errors on my console.
```
perl -MCPAN -e'install"LWP::UserAgent"'
perl -MCPAN -e'install"JSON"'
```
There might be a better way to do this. I am a total stranger to Perl.

**Comment by dimethyltriptamine** [comment]
There must be packages of those modules for your distribution, just run `<command you use to search packages> perl | grep -i json`. In the case of void linux is `perl-JSON` and in case of Debian is `libjson-perl`. Same with `LWP::UserAgent`. Just look for LWP or something

**Comment by GNUxeava** [comment]
Aight.
