### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by GNUxeava** [dimethyltriptamine/peertube-cli#2]
If I am following the README right, all I have to do is supply a search query to the program. It keeps failing anyway.
![image](https://user-images.githubusercontent.com/21287366/140018290-dca82106-9477-4bb6-b330-9cc5536aaf16.png)

**Comment by dimethyltriptamine** [comment]
You have to put the `.ptclirc` in your home directory, otherwise peertube-cli will use "" as instance. Giving an error because there's no website. Otherwrise you can run `PTCLIRC="./.ptclirc" ./peertube-cli.pl` or `./peertube-cli --instance <whatever> --resolution=0 --player=mpv`
